#!/usr/bin/env python
import argparse

from song_picker import Song, SongPicker

argparser = argparse.ArgumentParser()
argparser.add_argument(
    "mp3_dir", help="Path to a directory containing " \
    "MP3 files, which must end in the .mp3 extension")
argparser.add_argument(
    "duration", help="The total duration the song list " \
    "should approach, but not exceed")

args = argparser.parse_args()

song_choices = Song.create_many_from_mp3_dir(args.mp3_dir)

song_subset = SongPicker.get_songs_for_duration(int(args.duration), song_choices)

def print_song(song):
    print "Title: %s\nArtist: %s\nLength: %d" % \
        (song.get_title(), song.get_artist(), (song.get_length()) / 60)

for song_index, song in enumerate(song_subset):
    print "Song %d\n================" % song_index
    print_song(song)
    print "\n"

