#!/usr/bin/env python
import argparse

from song_picker import Song, SongPicker

argparser = argparse.ArgumentParser()
argparser.add_argument(
    "mp3_dir", help="Path to a directory containing " \
    "MP3 files, which must end in the .mp3 extension")
argparser.add_argument(
    "duration", help="The total duration the song list " \
    "should approach, but not exceed")

args = argparser.parse_args()

song_choices = Song.create_many_from_mp3_dir(args.mp3_dir)

song_subset = SongPicker.get_songs_for_duration(int(args.duration), song_choices)

print song_subset
